version: '3.8'

services:
  node:
    build: ./frontend
    ports:
      - "3000:3000"  # Expose Node app to host on port 3000
    networks:
      - app-network

networks:
  app-network:
    external: false
